### PR TITLE
For git cloning with submodules 

### PR DESCRIPTION
**Pull request by durgabhavaniv**

### CODE REVIEW

**Comment by sumitn-xilinx** [comment]
@durgabhavaniv  - can you please answer my question in the previous comment?

**Comment by sumitn-xilinx** [comment]
by default it should be getting all the submodules.

**Comment by durgabhavaniv** [comment]
@sumitn-xilinx  sorry for late reply.

git clone https://github.com/Xilinx/Vitis-AI -> will not clone AI-Model-Zoo @ 7f3456b

where as using git clone --recurse-submodules https://github.com/Xilinx/Vitis-AI.git, will clone everything.

**Comment by sumitn-xilinx** [comment]
Thanks for confirmation. I have updated the README:

https://github.com/Xilinx/Vitis-AI/commit/67d20a0cf999796e3fff738bccdca3736f244f7e#diff-04c6e90faac2675aa89e2176d2eec7d8

**Pull request closed without merging**
