### PR TITLE
modified image extention in waa readme files

### PR DESCRIPTION
**Pull request by nkpavan**
@sumitn-xilinx , please review and merge.

### CODE REVIEW

**Comment by sina1989** [comment]
Hi

I see an accuracy loss when i want to run vitis ai samples for Alveo in

https://github.com/Xilinx/Vitis-AI/tree/master/alveo/examples/vitis_ai_alveo_samples

i followed instructions in

https://github.com/Xilinx/Vitis-AI/issues/41

i changed default xilinx_u200_xdma_201830_2 in instal.sh to  xilinx_u200_xdma_201830_1 and flashed my Alveo U200 card again. i reset card by "/opt/xilinx/xrt/bin xbutil reset" command but nothing solved. for example in deployment_modes example i get following report:

 

Using VAI_ALVEO_ROOT
------------------
/workspace/alveo

---------------------
Using LD_LIBRARY_PATH
---------------------

-------------------
Using LIBXDNN_PATH
-------------------
/opt/vitis_ai/conda/envs/vitis-ai-caffe/lib/libxfdnn.so

-------------------
PYTHONPATH
-------------------
/opt/vitis_ai/compiler

---------------------
Verifying XILINX_XRT
---------------------
XILINX_XRT : /opt/xilinx/xrt
PATH : /opt/xilinx/xrt/bin:/opt/vitis_ai/conda/envs/vitis-ai-caffe/bin:/opt/vitis_ai/conda/condabin:/opt/vitis_ai/conda/bin:/opt/vitis_ai/utility:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH : /opt/xilinx/xrt/lib:
PYTHONPATH : /opt/xilinx/xrt/python:/opt/vitis_ai/compiler
--- Using System XCLBIN ---
Running:
Test: test_classify
Model: googlenet_v1
Xclbin: /opt/xilinx/overlaybins/xdnnv3
Accelerator: 0

python test_classify.py --xclbin /opt/xilinx/overlaybins/xdnnv3 --netcfg ./data/googlenet_v1_8b_autoAllOpt.json --weights ./data/googlenet_v1_data.h5 --labels ./synset_words.txt --quantizecfg ./data/googlenet_v1_8b_xdnnv3.json --img_input_scale 1.0 --batch_sz 4 --vitis_rundir /tmp/vitis-sahand/786 --images dog.jpg
-------------------
Speaking to Butler
Response from Butler is:
errCode: errCode: 0
errCode String: SUCCESS
myHandle: 1
valid: 1

[XDNN] loading xclbin settings from /opt/xilinx/overlaybins/xdnnv3/xdnn_v3_96x16_2pe_8b_9mb_bank03.xclbin.json
[XDNN] using custom DDR banks 0,3
Path /tmp/vitis-sahand/786/weights.h5 is a file.
Loading weights/bias/quant_params to FPGA...

[XRT] git hash : 192e706aea53163a04c574f9b3fe9ed76b6ca471
[XDNN] git hash : 1247bc4c889955a653bfefd1777c3aa2db3b4a4e
[XDNN] kernel configuration
[XDNN] num cores : 2
[XDNN] dsp array width : 96
[XDNN] axi data width (in 32bits) : 16
[XDNN] img mem size : 9 MB
[XDNN] max instr num : 1536
[XDNN] max xbar entries : 4096
[XDNN] version : 3.2
[XDNN] 8-bit mode : 1
---------- Prediction 1/4 for /workspace/alveo/examples/deployment_modes/dog.jpg ----------
0.0021 "n04005630 prison, prison house"
0.0021 "n03000134 chainlink fence"
0.0021 "n03291819 envelope"
0.0019 "n04350905 suit, suit of clothes"
0.0019 "n02786058 Band Aid"

**Comment by sumitn-xilinx** [comment]
Hello. This should not be the case. Let us check it at our end.

**Comment by sumitn-xilinx** [comment]
You seem to be mixing up things. 
https://github.com/Xilinx/Vitis-AI/tree/master/alveo/examples/vitis_ai_alveo_samples are C++ examples. And you need to follow instructions in each folders like resnet50.
Just ran it, and it worked perfectly fine:

_-------------------
Speaking to Butler 
Response from Butler is: 
errCode: errCode: 0
errCode String: SUCCESS
myHandle: 7
valid: 1

[XDNN] loading xclbin settings from /opt/xilinx/overlaybins/xdnnv3/xdnn_v3_96x16_2pe_8b_9mb_bank03_2.xclbin.json
[XDNN] using custom DDR banks 0,3
Path model/weights.h5 is a file.
Loading weights/bias/quant_params to FPGA...

[XRT]    git hash                   : 192e706aea53163a04c574f9b3fe9ed76b6ca471
[XDNN]   git hash                   : 6665f90940d49ab8337893307a87aa1afd4db13e
[XDNN] kernel configuration
[XDNN]   num cores                  : 2
[XDNN]   dsp array width            : 96
[XDNN]   axi data width (in 32bits) : 16
[XDNN]   img mem size               : 9 MB
[XDNN]   max instr num              : 1536
[XDNN]   max xbar entries           : 4096
[XDNN]   version                    : 3.2
[XDNN]   8-bit mode                 : 1

Image : PIC_085.jpg
top[0] prob = 0.376024  name = Cardigan, Cardigan Welsh corgi
top[1] prob = 0.376024  name = Border collie
top[2] prob = 0.065343  name = collie
top[3] prob = 0.065343  name = kelpie
top[4] prob = 0.065343  name = English springer, English springer spaniel_


And with latest Vitis AI (1.1), you always us ..201830_2 DSA,

**Comment by sina1989** [comment]
Thanks for your response 
I ran resnet50 example from 
https://github.com/Xilinx/Vitis-AI/tree/master/alveo/examples/vitis_ai_alveo_samples
but the same error, I use 201830_2_DSA

Using VAI_ALVEO_ROOT
------------------
/workspace/alveo

---------------------
Verifying XILINX_XRM
---------------------
---------------------
Using LD_LIBRARY_PATH
---------------------
/opt/xilinx/xrt/lib:/opt/xilinx/xrt/lib:
-------------------
Using LIBXDNN_PATH
-------------------
/opt/vitis_ai/conda/envs/vitis-ai-caffe/lib/libxfdnn.so

-------------------
PYTHONPATH
-------------------
/opt/xilinx/xrt/python:/opt/xilinx/xrt/python:/opt/vitis_ai/compiler

---------------------
Verifying XILINX_XRT
---------------------
XILINX_XRT      : /opt/xilinx/xrt
PATH            : /opt/xilinx/xrt/bin:/opt/xilinx/xrt/bin:/opt/xilinx/xrt/bin:/opt/vitis_ai/conda/envs/vitis-ai-caffe/bin:/opt/vitis_ai/conda/condabin:/opt/vitis_ai/conda/bin:/opt/vitis_ai/utility:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH : /opt/xilinx/xrt/lib:/opt/xilinx/xrt/lib:/opt/xilinx/xrt/lib:
PYTHONPATH     : /opt/xilinx/xrt/python:/opt/xilinx/xrt/python:/opt/xilinx/xrt/python:/opt/vitis_ai/compiler
./build/resnet50_v1.exe: /opt/vitis_ai/conda/envs/vitis-ai-caffe/lib/libuuid.so.1: no version information available (required by /opt/xilinx/xrt/lib/libxilinxopencl.so.2)
./build/resnet50_v1.exe: /opt/vitis_ai/conda/envs/vitis-ai-caffe/lib/libuuid.so.1: no version information available (required by /opt/xilinx/xrt/lib/libxrt_core.so.2)
-------------------
Speaking to Butler 
Response from Butler is: 
errCode: errCode: 0
errCode String: SUCCESS
myHandle: 5
valid: 1

[XDNN] loading xclbin settings from /opt/xilinx/overlaybins/xdnnv3/xdnn_v3_96x16_2pe_8b_9mb_bank03_2.xclbin.json
[XDNN] using custom DDR banks 0,3
Path model/weights.h5 is a file.
Loading weights/bias/quant_params to FPGA...

[XRT]    git hash                   : 192e706aea53163a04c574f9b3fe9ed76b6ca471
[XDNN]   git hash                   : 1247bc4c889955a653bfefd1777c3aa2db3b4a4e
[XDNN] kernel configuration
[XDNN]   num cores                  : 2
[XDNN]   dsp array width            : 96
[XDNN]   axi data width (in 32bits) : 16
[XDNN]   img mem size               : 9 MB
[XDNN]   max instr num              : 1536
[XDNN]   max xbar entries           : 4096
[XDNN]   version                    : 3.2
[XDNN]   8-bit mode                 : 1

Image : PIC_085.jpg
top[0] prob = 0.001000  name = toilet tissue, toilet paper, bathroom tissue
top[1] prob = 0.001000  name = ear, spike, capitulum
top[2] prob = 0.001000  name = bolete
top[3] prob = 0.001000  name = hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa
top[4] prob = 0.001000  name = earthstar

**Pull request merged**
